Updated queued-replace documentation, added PDF optimization.

diff --git a/Makefile-helper b/Makefile-helper
--- a/Makefile-helper
+++ b/Makefile-helper
@@ -1,4 +1,18 @@
 #!/bin/bash
+##
+# \file       	Makefile-helper
+# \library    	Documents
+# \author     	Chris Ahlstrom
+# \date       	2015-11-01
+# \update     	2017-05-07
+# \version    	$Revision$
+# \license    	$XPC_SUITE_GPL_LICENSE$
+#
+# 		Makefile for the sequencer64-doc project.
+#
+# Note the new usage of gs (Ghostscript) to optimize the PDF.  Obviously, one
+# must have Ghostscript installed.  This optimization reduces the near 40 Mb
+# PDF down to about 4 Mb in size, with no significant reduction in quality.
 
 MKERROR="no"
 
@@ -12,6 +26,16 @@ if [ "$1" == "" ] ; then
    if [ "$MKERROR" == "no" ] ; then
       cp tex/*.pdf pdf
 		rm tex/*.pdf
+		pushd pdf
+		mv sequencer64-user-manual.pdf s-temp.pdf
+gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dQUIET -dBATCH \
+ -sOutputFile=sequencer64-user-manual.pdf s-temp.pdf
+ 		if [ $? == 0 ] ; then
+			rm s-temp.pdf
+		else
+			echo "? Could not reduce the size of the PDF"
+		fi
+		popd
    fi
 elif [ "$1" == "clean" ] ; then
    pushd tex
